title: pilotpirxie's blog
description: Where I log my mostly technical side quests
email: 10637666+pilotpirxie@users.noreply.github.com
author: pilotpirxie
baseurl: ""
url: "https://pilotpirxie.github.io"

# Social Profiles
github_username: pilotpirxie

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
